kind: Service
apiVersion: v1
metadata:
  name: nginx-service
  namespace: lab06
spec:
  selector:
    app: nginx-front
  type: NodePort
  ports:
    - port: 8000
      targetPort: 80
      nodePort: 30123