apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-deploy
  namespace: assignment2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog
  template:
    metadata:
      labels:
        app: blog
    spec:
      containers:
      - name: wp
        image: wordpress:latest
        env:
        - name: WORDPRESS_DB_HOST
          value: 172.16.255.89:10000
        - name: WORDPRESS_DB_USER
          value: wordpress
        - name: WORDPRESS_DB_PASSWORD
          value: wordpress
        - name: WORDPRESS_DB_NAME
          value: wordpress
        ports:
        - containerPort: 80

---

kind: Service
apiVersion: v1
metadata:
  name: blog-service
  namespace: assignment2
spec:
  type: NodePort
  selector:
    app: blog
  ports:
  - nodePort: 30003
    port: 80
    targetPort: 80