apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deploy
  namespace: assignment2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_USER
          value: wordpress
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_PASSWORD
          value: wordpress
        - name: MYSQL_ROOT_PASSWORD
          value: wordpress
        ports:
        - containerPort: 3306

---

kind: Service
apiVersion: v1
metadata:
  name: db-service
  namespace: assignment2
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
  - port: 10000
    targetPort: 3306